### ISSUE TITLE
AmazonDynamoDBFullAccess Is Too Much Access

### ISSUE THREAD

**Issue by rsharrott** [SumoLogic/sumologic-mongodb-atlas#5]
AmazonDynamoDBFullAccess gives full access to every DynamoDB table in a given AWS account. This is a security risk as this will not likely be given the same scrutiny as other code. 

It would be better to ship a tighter policy that explicitly lays out only the code needs to access the table, and provision the table in the cloudformation template.

```yaml
- PolicyName: AllowDynamoUpdate
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:GetRecords
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${rDynamoDbtable}
          Version: 2012-10-17
```
